name: 'Close Issue'
description: 'A GitHub action to close an issue'
inputs:
  token:
    required: false
    description: 'GitHub auth token'
    default: ${{ github.token }}
  repository:
    required: false
    description: 'The GitHub repository containing the issue'
    default: ${{ github.repository }}
  issue-number:
    required: false
    description: 'The number of the issue to close'
    default: ${{ github.event.issue.number }}
  close-reason:
    required: false
    description: 'Reason for closing the issue, "completed" or "not_planned"'
    default: 'completed'
  comment:
    required: false
    description: 'A comment to make on the issue before closing'
  labels:
    required: false
    description: 'A comma or newline separated list of labels.'
runs:
  using: composite
  steps:
    - name: Set parameters
      id: params
      shell: bash
      env:
        CLOSE_REASON: ${{ inputs.close-reason }}
        LABELS: ${{ inputs.labels }}
      run: |
        if [ "$CLOSE_REASON" == "not_planned" ]; then
          echo close-reason="not planned" >> $GITHUB_OUTPUT
        else
          echo close-reason="completed" >> $GITHUB_OUTPUT
        fi

        # Convert labels to comma separated list
        if [ -n "$LABELS" ]; then
          labels=$(echo "$LABELS" | tr '\n' ',' | sed 's/,$//')
          # Remove trailing comma and whitespace
          labels=$(echo "$labels" | sed 's/,$//' | sed 's/[[:space:]]//g')
          echo labels="$labels" >> $GITHUB_OUTPUT
        fi

    - name: Close Issue
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        COMMENT: ${{ inputs.comment }}
        REPOSITORY: ${{ inputs.repository }}
        CLOSE_REASON: ${{ steps.params.outputs.close-reason }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
      run: |
        comment_args=()
        if [ -n "$COMMENT" ]; then
          comment_args=(--comment "$COMMENT")
        fi
        gh issue close -R "$REPOSITORY" \
          --reason "$CLOSE_REASON" \
          "${comment_args[@]}" \
          "$ISSUE_NUMBER"

    - name: Add Labels
      if: steps.params.outputs.labels != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        LABELS: ${{ steps.params.outputs.labels }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
      run: |
        gh issue edit -R "$REPOSITORY" \
          --add-label "$LABELS" \
          "$ISSUE_NUMBER"

branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
