name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: action.yml
          path: action.yml

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: action.yml
          path: .

      - name: Create issue content
        run: echo "#[CI] test ${{ matrix.os }}" > issue.md

      - name: Test create issue from file
        id: ciff
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: '[CI] test ${{ matrix.os }}'
          content-filepath: ./issue.md

      - name: Close Issue
        uses: ./
        with:
          issue-number: ${{ steps.ciff.outputs.issue-number }}
          comment: |
            [CI]
            test ${{ matrix.os }}
          labels: |
            wontfix
            ci-test
